name: appwrite_function
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  dart_appwrite: ^7.1.0
  # To use these dependencies in appwrite cloud function which supports Dart 2.17 currently
  openai_api:
    git:
      url: https://github.com/rohitsangwan01/openai_dart.git
      ref: lower_dart_sdk
  televerse:
    git:
      url: https://github.com/rohitsangwan01/televerse.git
      ref: 2a04543791d9820ea037cd429939b829b00574eb

dev_dependencies:
  lints: ^2.0.1
